"""
Lore - Assistant Core
Shared AI logic used by both the CLI and the Streamlit UI.
"""

import ollama
import re

from src.config import CHAT_MODEL, MAX_HISTORY_MESSAGES
from src.agent.router import decide_action
from src.agent.tools import TOOLS


SYSTEM_PROMPT = """
You are Lore, a local AI assistant that helps users explore fictional worlds, characters, and stories.

Rules:
- Answer using the provided context when available.
- If the context does not contain the answer, say so honestly.
- Do not invent facts.
- Keep answers clear, concise, and conversational.
- Never output HTML.
- Never use div tags, markdown wrappers, or UI formatting.
"""


def clean_response(text):
    """
    Remove accidental HTML generated by the model.
    The UI handles all HTML formatting.
    """

    text = re.sub(r"<[^>]*>", "", text)

    return text.strip()



def ask_ai(question, conversation_history):
    """
    Route the question to the appropriate tool (if any),
    then use the LLM to generate a grounded response.
    """

    tool_name, args = decide_action(question)

    sources = []


    if tool_name == "none":

        messages = (
            [{"role": "system", "content": SYSTEM_PROMPT}]
            + conversation_history
            + [{"role": "user", "content": question}]
        )


    else:

        tool_context, sources = TOOLS[tool_name]["run"](args)


        prompt = f"""
Use the following information to answer the user's question.

Information:
{tool_context}

Question:
{question}

Remember:
- Use only the information provided.
- Do not guess.
- Reply with plain text only.
"""


        messages = (
            [{"role": "system", "content": SYSTEM_PROMPT}]
            + conversation_history
            + [{"role": "user", "content": prompt}]
        )


    response = ollama.chat(
        model=CHAT_MODEL,
        messages=messages,
    )


    answer = response["message"]["content"]

    # remove accidental HTML
    answer = clean_response(answer)


    conversation_history.append(
        {
            "role": "user",
            "content": question
        }
    )

    conversation_history.append(
        {
            "role": "assistant",
            "content": answer
        }
    )


    conversation_history[:] = conversation_history[-MAX_HISTORY_MESSAGES:]


    return answer, sources, tool_name